/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.kime.subfeed;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import net.sf.sevenzipjbinding.simple.ISimpleInArchiveItem;

/**
 *
 * @author Kime
 */
public class Select1 extends javax.swing.JPanel {

    private static final DefaultListModel model = new DefaultListModel<Feed>();

    /**
     * Creates new form Select1
     */
    public Select1() {
        initComponents();
    }

    public static void addItem(final Feed feed) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                model.addElement(feed);
            }
        });
    }

    public static void clearItems() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                model.clear();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jScrollPane1.setToolTipText("");

        jList1.setModel(model);
        jList1.setToolTipText("");
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            final Feed feed = (Feed) model.get(index);
            System.out.println(feed.sid);
            
            Select2.clearItems();
            SubWindow.setPane(new Select2());

            new Thread() {
                @Override
                public void run() {
                    String dlLink = SubFeed.parseDownLink(feed.sid);
                    List<ISimpleInArchiveItem> list = SubFeed.downloadSub(dlLink);
                    for (ISimpleInArchiveItem item : list) {
                        Select2.addItem(new Subtitle(feed.title, item));
                    }

                }
            }.start();

        }
    }//GEN-LAST:event_jList1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
